pipeline {
    agent any
    tools {
        maven 'Maven_3.8.5' // Replace with the name/version of Maven installed on your Jenkins
    }
    stages {
        stage('Checkout') {
            steps {
                // Checkout code from GitHub
                git url: 'https://github.com/meetp0108/WelcomeApp.git', branch: 'main'
            }
        }
        stage('Build') {
            steps {
                // Run Maven build
                withMaven(maven: 'Maven_3.8.5') { // Ensure Maven is properly configured
                    sh "mvn clean verify"
                }
            }
        }
        stage('Test') {
            steps {
                // Run Maven tests (if any)
                sh 'mvn test'
            }
        }
        stage('Deploy') {
            steps {
                echo 'Deploying application...'
            }
        }
    }
    post {
        success {
            echo 'Build and tests succeeded!'
        }
        failure {
            echo 'Build or tests failed.'
        }
    }
}
